package com.coretek.pack.service;

import com.coretek.pack.model.InstallPack;
import com.coretek.pack.model.InstallPackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInstallPackService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int countByExample(InstallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int deleteByExample(InstallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int insert(InstallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int insertSelective(InstallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    List<InstallPack> selectByExample(InstallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    InstallPack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InstallPack record, @Param("example") InstallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InstallPack record, @Param("example") InstallPackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InstallPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InstallPack record);
}