package com.coretek.pack.dao;

import com.coretek.pack.model.InstallPackView;
import com.coretek.pack.model.InstallPackViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstallPackViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int countByExample(InstallPackViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int deleteByExample(InstallPackViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int insert(InstallPackView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int insertSelective(InstallPackView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    List<InstallPackView> selectByExample(InstallPackViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InstallPackView record, @Param("example") InstallPackViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install_pack_view
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InstallPackView record, @Param("example") InstallPackViewExample example);
}