package com.coretek.pack.dao;

import com.coretek.pack.model.PackMode;
import com.coretek.pack.model.PackModeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int countByExample(PackModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int deleteByExample(PackModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int insert(PackMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int insertSelective(PackMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    List<PackMode> selectByExample(PackModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    PackMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PackMode record, @Param("example") PackModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PackMode record, @Param("example") PackModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PackMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_mode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PackMode record);
}