package com.coretek.pack.model;

import java.util.Date;

public class InstallPackView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.date_time_str
     *
     * @mbggenerated
     */
    private String dateTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.indate
     *
     * @mbggenerated
     */
    private Integer indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.install_pack_path
     *
     * @mbggenerated
     */
    private String installPackPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.version_info
     *
     * @mbggenerated
     */
    private String versionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.pack_mode_structure
     *
     * @mbggenerated
     */
    private String packModeStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.pack_mode_id
     *
     * @mbggenerated
     */
    private Integer packModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack_view.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.user_name
     *
     * @return the value of install_pack_view.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.user_name
     *
     * @param userName the value for install_pack_view.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.date_time
     *
     * @return the value of install_pack_view.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.date_time
     *
     * @param dateTime the value for install_pack_view.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.project_name
     *
     * @return the value of install_pack_view.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.project_name
     *
     * @param projectName the value for install_pack_view.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.product_name
     *
     * @return the value of install_pack_view.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.product_name
     *
     * @param productName the value for install_pack_view.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.date_time_str
     *
     * @return the value of install_pack_view.date_time_str
     *
     * @mbggenerated
     */
    public String getDateTimeStr() {
        return dateTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.date_time_str
     *
     * @param dateTimeStr the value for install_pack_view.date_time_str
     *
     * @mbggenerated
     */
    public void setDateTimeStr(String dateTimeStr) {
        this.dateTimeStr = dateTimeStr == null ? null : dateTimeStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.indate
     *
     * @return the value of install_pack_view.indate
     *
     * @mbggenerated
     */
    public Integer getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.indate
     *
     * @param indate the value for install_pack_view.indate
     *
     * @mbggenerated
     */
    public void setIndate(Integer indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.install_pack_path
     *
     * @return the value of install_pack_view.install_pack_path
     *
     * @mbggenerated
     */
    public String getInstallPackPath() {
        return installPackPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.install_pack_path
     *
     * @param installPackPath the value for install_pack_view.install_pack_path
     *
     * @mbggenerated
     */
    public void setInstallPackPath(String installPackPath) {
        this.installPackPath = installPackPath == null ? null : installPackPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.version_info
     *
     * @return the value of install_pack_view.version_info
     *
     * @mbggenerated
     */
    public String getVersionInfo() {
        return versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.version_info
     *
     * @param versionInfo the value for install_pack_view.version_info
     *
     * @mbggenerated
     */
    public void setVersionInfo(String versionInfo) {
        this.versionInfo = versionInfo == null ? null : versionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.pack_mode_structure
     *
     * @return the value of install_pack_view.pack_mode_structure
     *
     * @mbggenerated
     */
    public String getPackModeStructure() {
        return packModeStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.pack_mode_structure
     *
     * @param packModeStructure the value for install_pack_view.pack_mode_structure
     *
     * @mbggenerated
     */
    public void setPackModeStructure(String packModeStructure) {
        this.packModeStructure = packModeStructure == null ? null : packModeStructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.pack_mode_id
     *
     * @return the value of install_pack_view.pack_mode_id
     *
     * @mbggenerated
     */
    public Integer getPackModeId() {
        return packModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.pack_mode_id
     *
     * @param packModeId the value for install_pack_view.pack_mode_id
     *
     * @mbggenerated
     */
    public void setPackModeId(Integer packModeId) {
        this.packModeId = packModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack_view.id
     *
     * @return the value of install_pack_view.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack_view.id
     *
     * @param id the value for install_pack_view.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}