package com.coretek.pack.model;

public class InstallPack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack.person_id
     *
     * @mbggenerated
     */
    private Integer personId;

    public InstallPack() {
	}

	public InstallPack(Integer personId, Integer packModeId,
			Integer logInfoId, String installPackPath) {
		super();
		this.personId = personId;
		this.packModeId = packModeId;
		this.logInfoId = logInfoId;
		this.installPackPath = installPackPath;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack.pack_mode_id
     *
     * @mbggenerated
     */
    private Integer packModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack.log_info_id
     *
     * @mbggenerated
     */
    private Integer logInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_pack.install_pack_path
     *
     * @mbggenerated
     */
    private String installPackPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack.id
     *
     * @return the value of install_pack.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack.id
     *
     * @param id the value for install_pack.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack.person_id
     *
     * @return the value of install_pack.person_id
     *
     * @mbggenerated
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack.person_id
     *
     * @param personId the value for install_pack.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack.pack_mode_id
     *
     * @return the value of install_pack.pack_mode_id
     *
     * @mbggenerated
     */
    public Integer getPackModeId() {
        return packModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack.pack_mode_id
     *
     * @param packModeId the value for install_pack.pack_mode_id
     *
     * @mbggenerated
     */
    public void setPackModeId(Integer packModeId) {
        this.packModeId = packModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack.log_info_id
     *
     * @return the value of install_pack.log_info_id
     *
     * @mbggenerated
     */
    public Integer getLogInfoId() {
        return logInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack.log_info_id
     *
     * @param logInfoId the value for install_pack.log_info_id
     *
     * @mbggenerated
     */
    public void setLogInfoId(Integer logInfoId) {
        this.logInfoId = logInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_pack.install_pack_path
     *
     * @return the value of install_pack.install_pack_path
     *
     * @mbggenerated
     */
    public String getInstallPackPath() {
        return installPackPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_pack.install_pack_path
     *
     * @param installPackPath the value for install_pack.install_pack_path
     *
     * @mbggenerated
     */
    public void setInstallPackPath(String installPackPath) {
        this.installPackPath = installPackPath == null ? null : installPackPath.trim();
    }
}