package com.coretek.pack.model;

import java.util.Date;

public class LogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.pack_mode_structure
     *
     * @mbggenerated
     */
    private String packModeStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.indate
     *
     * @mbggenerated
     */
    private Integer indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.version_info
     *
     * @mbggenerated
     */
    private String versionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.svn_net_path
     *
     * @mbggenerated
     */
    private String svnNetPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.date_time_str
     *
     * @mbggenerated
     */
    private String dateTimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.id
     *
     * @return the value of log_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.id
     *
     * @param id the value for log_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.content
     *
     * @return the value of log_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.content
     *
     * @param content the value for log_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.user_name
     *
     * @return the value of log_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.user_name
     *
     * @param userName the value for log_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.date_time
     *
     * @return the value of log_info.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.date_time
     *
     * @param dateTime the value for log_info.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.pack_mode_structure
     *
     * @return the value of log_info.pack_mode_structure
     *
     * @mbggenerated
     */
    public String getPackModeStructure() {
        return packModeStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.pack_mode_structure
     *
     * @param packModeStructure the value for log_info.pack_mode_structure
     *
     * @mbggenerated
     */
    public void setPackModeStructure(String packModeStructure) {
        this.packModeStructure = packModeStructure == null ? null : packModeStructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.indate
     *
     * @return the value of log_info.indate
     *
     * @mbggenerated
     */
    public Integer getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.indate
     *
     * @param indate the value for log_info.indate
     *
     * @mbggenerated
     */
    public void setIndate(Integer indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.version_info
     *
     * @return the value of log_info.version_info
     *
     * @mbggenerated
     */
    public String getVersionInfo() {
        return versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.version_info
     *
     * @param versionInfo the value for log_info.version_info
     *
     * @mbggenerated
     */
    public void setVersionInfo(String versionInfo) {
        this.versionInfo = versionInfo == null ? null : versionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.svn_net_path
     *
     * @return the value of log_info.svn_net_path
     *
     * @mbggenerated
     */
    public String getSvnNetPath() {
        return svnNetPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.svn_net_path
     *
     * @param svnNetPath the value for log_info.svn_net_path
     *
     * @mbggenerated
     */
    public void setSvnNetPath(String svnNetPath) {
        this.svnNetPath = svnNetPath == null ? null : svnNetPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.project_name
     *
     * @return the value of log_info.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.project_name
     *
     * @param projectName the value for log_info.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.product_name
     *
     * @return the value of log_info.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.product_name
     *
     * @param productName the value for log_info.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.remark
     *
     * @return the value of log_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.remark
     *
     * @param remark the value for log_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.date_time_str
     *
     * @return the value of log_info.date_time_str
     *
     * @mbggenerated
     */
    public String getDateTimeStr() {
        return dateTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.date_time_str
     *
     * @param dateTimeStr the value for log_info.date_time_str
     *
     * @mbggenerated
     */
    public void setDateTimeStr(String dateTimeStr) {
        this.dateTimeStr = dateTimeStr == null ? null : dateTimeStr.trim();
    }
}