package com.coretek.pack.model;

import java.util.Date;

public class logInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.pack_mode_id
     *
     * @mbggenerated
     */
    private Integer packModeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.id
     *
     * @return the value of log_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.id
     *
     * @param id the value for log_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.content
     *
     * @return the value of log_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.content
     *
     * @param content the value for log_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.user_id
     *
     * @return the value of log_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.user_id
     *
     * @param userId the value for log_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.date_time
     *
     * @return the value of log_info.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.date_time
     *
     * @param dateTime the value for log_info.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.pack_mode_id
     *
     * @return the value of log_info.pack_mode_id
     *
     * @mbggenerated
     */
    public Integer getPackModeId() {
        return packModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.pack_mode_id
     *
     * @param packModeId the value for log_info.pack_mode_id
     *
     * @mbggenerated
     */
    public void setPackModeId(Integer packModeId) {
        this.packModeId = packModeId;
    }
}