package com.coretek.pack.model;

public class PackMode {
	
	public PackMode(){
		platformLocalPath = "";
		isUpdateKey = 0;
		isUpdateUuid = 0;
		status = 0;
		svnNetPath = "";
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.platform_local_path
     *
     * @mbggenerated
     */
    private String platformLocalPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.is_svn_check
     *
     * @mbggenerated
     */
    private Integer isSvnCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.svn_net_path
     *
     * @mbggenerated
     */
    private String svnNetPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.version_info
     *
     * @mbggenerated
     */
    private Integer versionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.indate
     *
     * @mbggenerated
     */
    private Integer indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.system_version
     *
     * @mbggenerated
     */
    private String systemVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.structure_type
     *
     * @mbggenerated
     */
    private String structureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.is_update_key
     *
     * @mbggenerated
     */
    private Integer isUpdateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.is_update_uuid
     *
     * @mbggenerated
     */
    private Integer isUpdateUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pack_mode.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.id
     *
     * @return the value of pack_mode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.id
     *
     * @param id the value for pack_mode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.platform_local_path
     *
     * @return the value of pack_mode.platform_local_path
     *
     * @mbggenerated
     */
    public String getPlatformLocalPath() {
        return platformLocalPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.platform_local_path
     *
     * @param platformLocalPath the value for pack_mode.platform_local_path
     *
     * @mbggenerated
     */
    public void setPlatformLocalPath(String platformLocalPath) {
        this.platformLocalPath = platformLocalPath == null ? null : platformLocalPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.is_svn_check
     *
     * @return the value of pack_mode.is_svn_check
     *
     * @mbggenerated
     */
    public Integer getIsSvnCheck() {
        return isSvnCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.is_svn_check
     *
     * @param isSvnCheck the value for pack_mode.is_svn_check
     *
     * @mbggenerated
     */
    public void setIsSvnCheck(Integer isSvnCheck) {
        this.isSvnCheck = isSvnCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.svn_net_path
     *
     * @return the value of pack_mode.svn_net_path
     *
     * @mbggenerated
     */
    public String getSvnNetPath() {
        return svnNetPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.svn_net_path
     *
     * @param svnNetPath the value for pack_mode.svn_net_path
     *
     * @mbggenerated
     */
    public void setSvnNetPath(String svnNetPath) {
        this.svnNetPath = svnNetPath == null ? null : svnNetPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.version_info
     *
     * @return the value of pack_mode.version_info
     *
     * @mbggenerated
     */
    public Integer getVersionInfo() {
        return versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.version_info
     *
     * @param versionInfo the value for pack_mode.version_info
     *
     * @mbggenerated
     */
    public void setVersionInfo(Integer versionInfo) {
        this.versionInfo = versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.indate
     *
     * @return the value of pack_mode.indate
     *
     * @mbggenerated
     */
    public Integer getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.indate
     *
     * @param indate the value for pack_mode.indate
     *
     * @mbggenerated
     */
    public void setIndate(Integer indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.system_version
     *
     * @return the value of pack_mode.system_version
     *
     * @mbggenerated
     */
    public String getSystemVersion() {
        return systemVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.system_version
     *
     * @param systemVersion the value for pack_mode.system_version
     *
     * @mbggenerated
     */
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion == null ? null : systemVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.structure_type
     *
     * @return the value of pack_mode.structure_type
     *
     * @mbggenerated
     */
    public String getStructureType() {
        return structureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.structure_type
     *
     * @param structureType the value for pack_mode.structure_type
     *
     * @mbggenerated
     */
    public void setStructureType(String structureType) {
        this.structureType = structureType == null ? null : structureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.is_update_key
     *
     * @return the value of pack_mode.is_update_key
     *
     * @mbggenerated
     */
    public Integer getIsUpdateKey() {
        return isUpdateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.is_update_key
     *
     * @param isUpdateKey the value for pack_mode.is_update_key
     *
     * @mbggenerated
     */
    public void setIsUpdateKey(Integer isUpdateKey) {
        this.isUpdateKey = isUpdateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.is_update_uuid
     *
     * @return the value of pack_mode.is_update_uuid
     *
     * @mbggenerated
     */
    public Integer getIsUpdateUuid() {
        return isUpdateUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.is_update_uuid
     *
     * @param isUpdateUuid the value for pack_mode.is_update_uuid
     *
     * @mbggenerated
     */
    public void setIsUpdateUuid(Integer isUpdateUuid) {
        this.isUpdateUuid = isUpdateUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pack_mode.status
     *
     * @return the value of pack_mode.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pack_mode.status
     *
     * @param status the value for pack_mode.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}