package com.coretek.pack.model;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.permission
     *
     * @mbggenerated
     */
    private Integer permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.svn_username
     *
     * @mbggenerated
     */
    private String svnUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.svn_password
     *
     * @mbggenerated
     */
    private String svnPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.password
     *
     * @return the value of person.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.password
     *
     * @param password the value for person.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.permission
     *
     * @return the value of person.permission
     *
     * @mbggenerated
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.permission
     *
     * @param permission the value for person.permission
     *
     * @mbggenerated
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.svn_username
     *
     * @return the value of person.svn_username
     *
     * @mbggenerated
     */
    public String getSvnUsername() {
        return svnUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.svn_username
     *
     * @param svnUsername the value for person.svn_username
     *
     * @mbggenerated
     */
    public void setSvnUsername(String svnUsername) {
        this.svnUsername = svnUsername == null ? null : svnUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.svn_password
     *
     * @return the value of person.svn_password
     *
     * @mbggenerated
     */
    public String getSvnPassword() {
        return svnPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.svn_password
     *
     * @param svnPassword the value for person.svn_password
     *
     * @mbggenerated
     */
    public void setSvnPassword(String svnPassword) {
        this.svnPassword = svnPassword == null ? null : svnPassword.trim();
    }
}